### ISSUE TITLE
Single sign-on for forum

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#142]
For now, we can just explain that it's two separate accounts.

**Comment by alexandermendes** [comment]
See https://github.com/wuethrich44/flarum-ext-sso/blob/master/README.md

**Comment by alexandermendes** [comment]
To avoid writing another plugin this will require the frontend to implement some functions to integrate with Flarum. This should be turned off by default and written up in the docs.

**Comment by alexandermendes** [comment]
Took the writing of another plugin as apparently nothing really exists for our forum software!

https://github.com/alexandermendes/nuxt-flarum

I might attempt to push that to a more official repo after more testing

**Comment by alexandermendes** [comment]
I think it's done, go ahead and close when you're ready 😄

**Comment by mialondon** [comment]
Have you seen any user comments? It seems straightforward to me but we could check whether it confuses people signing up for the first time.

**Comment by alexandermendes** [comment]
Haven't noticed anyone saying they have had issues. Really it just takes you to different looking sign in/sign up pages, can't see that being too confusing for anyone!
