### ISSUE TITLE
I can return to a previous image after submitting, but I cannot correct it.

### ISSUE THREAD

**Issue by Ada1000** [LibCrowds/libcrowds#150]

**Comment by alexandermendes** [comment]
This is down to a fundamental way in which the task retirement process works. We're asking for, say, 3 contributions per task and we have to know when this task can be closed and the results processed. If someone is the third person to complete the task, the second it's submitted it gets sent off to our results analysis server for processing (potentially the results become searchable soon afterwards). If someone was to then come back 5 minutes, or a week later and decide they want to change their answer it's too late, we've already produced our final result!

But this does come up quite a lot and clearly needs some better explanation. I'll start an FAQ soon and add something about this in there.

I have also just added a 'Confirm on Submit' option to the viewer module, which will be available on the main site soon, that warns there is no going back!

Thanks.

**Comment by mialondon** [comment]
Moved to trello FAQ notes.
