### ISSUE TITLE
Post-usability testing fixes: change 'Contribute' heading to 'Take part'

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#173]
Possibly make into a variable at the same time.

**Comment by alexandermendes** [comment]
@mialondon This is actually a bit problematic as the word "contribution" directly relates to "task run". So there are **n** contributions per task, and therefore we say contribute so it all links up quite nicely! Also things like:

- "How your contributions make a difference"
- "Your contributions will have a direct impact on enabling future research"
- "You have made 100 contributions"

Not sure we really need to bother with this one.

**Comment by mialondon** [comment]
@alexandermendes it's just the heading so it's a bit more of a call to action, we'll still use 'contribute' elsewhere.

**Comment by alexandermendes** [comment]
Closing this, doesn't seem hugely important and the contribute page is established now. Eventually we can bring the navbar into scope for the CMS but would say it's not work it for now!

**Comment by mialondon** [comment]
'Get started' does a lot of the work that 'Contribute' doesn't (e.g. someone asked what 'Contribute' meant last night) so I'd still like to address it sooner rather than later.
