### ISSUE TITLE
Post-usability testing fixes: document where different bits of text are updated

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#181]
Maintain 'How to update site text and generate tasks' section of the wiki e.g. various bits are updated on project admin site or different github repositories.

**Comment by alexandermendes** [comment]
@mialondon So this is mostly done. For the core PyBossa stuff I do kind of want to avoid just replicating this http://docs.pybossa.com/en/latest/user/project_settings.html

**Comment by alexandermendes** [comment]
Having said that, I do want to generate full documentation for the theme, but only once all of our admin interfaces are in place (#141)

**Comment by alexandermendes** [comment]
Closing as this will all be covered by #141

**Comment by mialondon** [comment]
Re-opening for the Pybossa documentation link (for now).

**Comment by mialondon** [comment]
An FAQ-style 'where do I update x text' might be a useful index to the documentation.

**Comment by alexandermendes** [comment]
https://docs.libcrowds.com will be the place for all documentation, all current admin sections documented in the upcoming release, and it has a search box.
