### ISSUE TITLE
Post-usability testing fix: update 'add a note' text

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#185]
To: 'Seen something interesting, or report an issue'.

Help text should be updated to explain what happens to information supplied on notes - where it's displayed etc

**Comment by alexandermendes** [comment]
I would still lean towards the notes being something to help staff (us) during processing of the data. It would be nice to encourage use of the forum as a the place to chat about interesting things.

However they are saved as Comment Annotations, so if it turns out we can use them elsewhere in future that should be easy enough

**Comment by mialondon** [comment]
Not every page is worth a forum post, but it's nice to note something interesting.

**Comment by mialondon** [comment]
Based on feedback so far, it seems like we should separate notes from tasks, and let people add notes at any point. @alexandermendes I think @ndalyrose mentioned a convert-a-card forum thread where people requested the ability to tell us about collection items - can you recall the details?

**Comment by mialondon** [comment]
Feedback from one user:

"Enable notes to be added after submit. The faster one goes, the more likely one is to have a thought after the fact."

**Comment by alexandermendes** [comment]
Yep, we added notes to the tasks for covert a card too. Just as a simple "add a comment" and that has worked fine.

This comes back to the old "why can't I update an answer after it has been submitted", explained at length elsewhere!

I actually think we should just remove the images from the queue once completed to save confusion. Separating notes from the task sounds like a huge hassle. Where are they stored in the database model? How are they linked to tasks?

Starting to think we should've used Disqus or something but it's a paid service without the ads

**Comment by alexandermendes** [comment]
This also brings me back to how I really think we should have a confirm/cancel to submit your final answer button. Ill check out the data later but i suspect we have a lot of missing regions. Also this would help people understand that this is indeed their final answer!

**Comment by alexandermendes** [comment]
As I play around with the data, this might be interesting - all of our comments from the now completed Margate project:

```
[  
   {  
      "body":{  
         "type":"TextualBody",
         "purpose":"commenting",
         "value":"Not a playbill. ",
         "format":"text/plain"
      },
      "motivation":"commenting",
      "target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x000094",
      "created":"2017-09-07T16:22:29.416Z",
      "modified":"2017-09-07T16:22:32.131Z",
      "generated":"2017-09-07T16:22:29.416Z",
      "@context":"http://www.w3.org/ns/anno.jsonld",
      "type":"Annotation",
      "id":"97b63351-c1a4-456e-8871-b299aa684639"
   },
   {  
      "body":{  
         "type":"TextualBody",
         "purpose":"commenting",
         "value":"This page is blank.",
         "format":"text/plain"
      },
      "motivation":"commenting",
      "target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x00007c",
      "created":"2017-08-31T10:09:55.082Z",
      "modified":"2017-08-31T10:09:57.777Z",
      "generated":"2017-08-31T10:09:55.082Z",
      "@context":"http://www.w3.org/ns/anno.jsonld",
      "type":"Annotation",
      "id":"4bad6560-9150-4558-bee7-a6b7fe055326"
   },
   {  
      "body":{  
         "type":"TextualBody",
         "purpose":"commenting",
         "value":"interesting font",
         "format":"text/plain"
      },
      "motivation":"commenting",
      "target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x0000bc",
      "created":"2017-08-31T11:00:26.238Z",
      "modified":"2017-08-31T11:00:32.127Z",
      "generated":"2017-08-31T11:00:26.238Z",
      "@context":"http://www.w3.org/ns/anno.jsonld",
      "type":"Annotation",
      "id":"41538ffa-68bb-40c8-9ddf-aa3518366761"
   },
   {  
      "body":{  
         "type":"TextualBody",
         "purpose":"commenting",
         "value":"Not a playbill",
         "format":"text/plain"
      },
      "motivation":"commenting",
      "target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x00007c",
      "created":"2017-09-04T16:31:42.439Z",
      "modified":"2017-09-04T16:31:43.941Z",
      "generated":"2017-09-04T16:31:42.439Z",
      "@context":"http://www.w3.org/ns/anno.jsonld",
      "type":"Annotation",
      "id":"3592aae4-d9e0-4119-ac1c-2347fc96d611"
   },
   {  
      "body":{  
         "type":"TextualBody",
         "purpose":"commenting",
         "value":"Not a playbill!",
         "format":"text/plain"
      },
      "motivation":"commenting",
      "target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x0000d5",
      "created":"2017-09-05T10:57:48.246Z",
      "modified":"2017-09-05T10:57:53.472Z",
      "generated":"2017-09-05T10:57:48.246Z",
      "@context":"http://www.w3.org/ns/anno.jsonld",
      "type":"Annotation",
      "id":"99b34dc5-8458-458c-991a-d1a059488d1b"
   },
   {  
      "body":{  
         "type":"TextualBody",
         "purpose":"commenting",
         "value":"Not a playbill",
         "format":"text/plain"
      },
      "motivation":"commenting",
      "target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x000094",
      "created":"2017-09-05T11:07:32.273Z",
      "modified":"2017-09-05T11:07:34.848Z",
      "generated":"2017-09-05T11:07:32.273Z",
      "@context":"http://www.w3.org/ns/anno.jsonld",
      "type":"Annotation",
      "id":"288c5a95-4b71-432c-92a1-0d7295c55349"
   }
]
```

6 comments from 376 task runs, so a comment rate of 0.02%.

**Comment by alexandermendes** [comment]
@mialondon I guess this one actually needs some clarification regarding our decision. So we can certainly change the button text.

To clarify my previously unclear comments questioning how we would store notes separately from answers - the database model is here https://github.com/Scifabric/pybossa/tree/master/pybossa/model and we're storing our notes, along with all other annotations (see below) in the info column of the task_run table.

Something I forgot to mention is that our notes are actually just Comment Annotations, which are defined as comments about the item as a whole, rather than a specific region or aspect of that item (see https://libcrowds.gitbooks.io/libcrowds-viewer-docs/content/annotations/comment.html). Only mentioning that to say that, as with everything else, quite a lot of thought has actually gone into this! The cool thing here is that the comments actually meaning something semantically (see "commenting" under https://www.w3.org/TR/annotation-model/#motivation-and-purpose). We will want to think about how we process these comments but it's entirely plausible that they could feed into things like the IIIF Content Search API.

Probably more info than you want but perhaps, after updating the note text, the rest can be tackled with better documentation for now!

**Comment by mialondon** [comment]
Notes from discussion with Alex and Christian (related to a bunch of 'for discussion' issues, sorry Alex!):

If we have notes in a browse view (a different decision), provide instructions on how 'to share this page in a forum discussion' as well as changing the text on the notes field. The idea is to nudge people into posting on the forum for back and forth discussions and not trying to use notes for this.

Providing a 'browse' interface would resolve the question of navigating back and forth in the task queue, thus resolving a related issue. It would provide access to all items, and to live data. Is it linked to the review task?

Computational review process for marked data - what if only one person marks it? Maybe include it anyway. When that's done, Alex to set up transcription task on staging so we can do usability tests with real data and update instructions and help text accordingly.

Manual review process - just comments or tick box to report item that needs review?

Transcribe task instructions - ask people to ignore genre if it's included.

Genres - for this title, is a genre listed? Type what you see. Result is a list of actual terms from the playbills, useful for scholars. Type ahead / auto-complete generated from the field. Instructions - don't include a, the. What else?

Additional research questions like 'for the benefit of', patronage of, song titles etc - we now have a platform for creating tasks for people but the onus is on person with the question to motivate participation. So no academics saying 'sure, that'd be useful' but not taking part in comms.

When new volumes up? Christian to send list of the next 6-10 to go up.

**Comment by alexandermendes** [comment]
Thanks for noting all of that down. So I'm just going to take this one off the current milestone, I'll deal with the button text thing in https://github.com/LibCrowds/vue-pybossa-frontend/issues/268, and then I'll tease this one out into separate issues when we start to look at the review page next week.
