### ISSUE TITLE
More guidance for people to click save only when all regions are marked

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#192]
@mialondon I think we should reconsider the 'confirm-on-submit' button, perhaps with less 'scary' language. A large chunk of our contributions are now only with one area marked as people (understandably) aren't sure whether they need to save each region or the page as a whole.

So we need something like "Are all titles on this page marked up? [ Yes ] [ No ]" with the No causing another remainder - "Please mark all titles on the page before saving".

Having a low barrier to entry is one thing but we do also need to ensure we get good data.

**Comment by mialondon** [comment]
Let's update the task instructions first and retest before writing more code, as people kicking the tyres on a project often behave differently than real crowdsourcers...

**Comment by alexandermendes** [comment]
Ok, will just move this over to the beta version for now

**Comment by alexandermendes** [comment]
This is looking increasingly important, it's already come up quite a lot 

E.g. https://community.libcrowds.com/d/5-more-than-one-title-on-a-playbill

**Comment by mialondon** [comment]
@alexandermendes what kind of modal/dialogue were you thinking? Ideally people would be able to tick 'Stop seeing this message' so they don't have to go through it each time.

**Comment by alexandermendes** [comment]
Sounds like a good idea to me and should be pretty straightforward (a cookie would be the standard way). Added to our next milestone!

**Comment by alexandermendes** [comment]
This came up again during the Kent Uni workshop. It seems to often take people some time to figure out how to save multiple titles.

**Comment by mialondon** [comment]
We can partly address it with the tutorial modal on load, and updated task instructions, but let's also consider the notification options.

**Comment by mialondon** [comment]
If they've only marked one title (or none) then dialogue: 'Most playbills have more than one title. Do you want to go back and check?' 'Yes, please' or 'No, there was only one title'

**Comment by alexandermendes** [comment]
So this one has been coming for some time, here's a basic version!

We will eventually want to make these messages and rules configurable via the admin interface, but this will do for now.

**Comment by mialondon** [comment]
Hoorah!

It'd be great to make the dialogue options match the microcopy, so that they said 'Go back to the sheet' and 'Submit anyway' (but with better words than that. Would that be part of the config options?

**Comment by mialondon** [comment]
Also it just told me I'd outlined one title when I hadn't outlined any (it was a programme of scenery rather than a playbill). I'll reopen this for now but we could also start a new issue for the more polished version.

**Comment by alexandermendes** [comment]
Ok, so as we have to bear in mind that we might one day want to use this for something other than playbills, this will be another set of config options.

It's counting annotations and comments count as an annotation so that will be where the miscount came from - assuming you added a note.

**Comment by mialondon** [comment]
I did add a note (to say that it wasn't a playbill) - thanks for the explanation! Should it count notes as marks in this instance?

It'd be good to usability test this before rolling out the next update - maybe we can use these issues as a guide for writing task tests.

**Comment by alexandermendes** [comment]
I suppose the easiest thing would be to just not count any comment annotations, so the confirmation box will still be triggered but show the right count

**Comment by alexandermendes** [comment]
Can we just go for "Go Back" Or "Continue" for the buttons - not sure if it makes a big enough difference to warrant another yet config option? This is going to become a pretty complex config option already.

**Comment by alexandermendes** [comment]
Rules are now configurable via the collection admin interface in terms of tag type and number required. So we can say that each image usually contains 2 titles, or 1 date, or 35 people etc.

The language may not specifically reflect the playbills but I don't think people will be too confused to read "Each image usually contains n" rather than "Each sheet usually contains n". If we go to that level it gets very complex and I'm already wary that people will struggle with the amount of config options we're going to end up putting in!
