### ISSUE TITLE
Don't see images to be annotated in Safari

### ISSUE THREAD

**Issue by ostephens** [LibCrowds/libcrowds#230]
Trying to annotate playbills at https://www.libcrowds.com/collection/playbills/project/identify_titles_theatre_royal_margate_1796-1797/presenter/

Using Safari Version 10.1.2 (12603.3.8) on macOS Sierra

Instead of seeing image, get a blank space in image viewer. No obvious error in javascript console so not sure what is happening to prevent the image loading/displaying

<img width="1052" alt="screen shot 2017-09-07 at 16 58 30" src="https://user-images.githubusercontent.com/576174/30172935-045aaca2-93ee-11e7-99df-55863cd16eef.png">

**Comment by alexandermendes** [comment]
Thanks again, I'll have a look when I get back to my own Mac.

I guess this demo of the viewer module doesn't work either (just to narrow it down a little)? https://libcrowds.github.io/libcrowds-viewer/

**Comment by ostephens** [comment]
@alexandermendes Just to confirm that demo of the viewer module doesn't work either under the same setup

**Comment by mialondon** [comment]
@ostephens we haven't been able to replicate this, could you give us any more information on your setup?

**Comment by ostephens** [comment]
@mialondon odd - I now can't replicate (although I'm now on Safari 11.0.0 on High Sierra, so can't entirely replicate my old setup)

**Comment by alexandermendes** [comment]
This could have just been the images failing to load from where they're hosted on our BL servers. This does happen occasionally, although it should then show an error along the lines of "Tiles failed to load over HTTP...".

I'll try to have another look at this next week. We should at least fix any error messages for cases where images don't load properly.

**Comment by alexandermendes** [comment]
Thanks for the version numbers by the way, so possibly something that was fixed in Safari 11. I'll cover this here https://github.com/LibCrowds/libcrowds/issues/446
