### ISSUE TITLE
Selected parts of image don't display in righthand panel

### ISSUE THREAD

**Issue by ostephens** [LibCrowds/libcrowds#231]
In the righthand panel (below instructions) on https://www.libcrowds.com/collection/playbills/project/identify_titles_theatre_royal_margate_1796-1797/presenter/

Don't see the areas of the image selected displayed, but often grey blocks (and on one occasion and different part of the image to the one selected).

E.g.

<img width="1111" alt="screen shot 2017-09-07 at 17 05 50" src="https://user-images.githubusercontent.com/576174/30173273-04926aec-93ef-11e7-8148-3ff703762bde.png">

I'd expect to see the correct bit of the image so I can select for re-editing or remove from the list

Tested on macOS Sierra using:

Safari Version 10.1.2 (12603.3.8)
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Firefox 55.0.3 (64-bit)

**Comment by alexandermendes** [comment]
Thanks, you should indeed be seeing the cropped areas of the image. In fact, it just copies the canvas content directly from the main one to other canvases in the edit list, so it's a bit strange that the screenshot is showing one and not the other. I'll check it out!

**Comment by alexandermendes** [comment]
So this one definitely looks like a style issues an I suspect a flexbox bug, we've got a few issues about this so I'll cover it here https://github.com/LibCrowds/libcrowds/issues/446
