### ISSUE TITLE
Scrolling on core app pages for mobile is broken

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#234]
With my Android phone I can't scroll down the page properly but only on the main homepage (the `collection/` pages seem to be ok).

**Comment by mialondon** [comment]
@alexandermendes should we ask the digital research team to test on their mobile and tablet devices?

**Comment by alexandermendes** [comment]
Yep good idea!

**Comment by mialondon** [comment]
The playbill isn't appearing on my iPod running iOS 10.3.3 but the other pages scroll ok.

**Comment by mialondon** [comment]
@alexandermendes what exactly do we want to ask them, and are you ok with feedback by email if people don't have github accounts?

**Comment by alexandermendes** [comment]
Yeah well I suppose it's just a case of browsing around and seeing if any pages don't scroll or buttons don't work etc. I'll come up with a better way of saying that though!

Really it's not the most reliable way of doing things, I would ultimately like proper cross-browser tests, probably using https://saucelabs.com/, but that could be a few weeks off (have started writing the tests though)!

**Comment by alexandermendes** [comment]
Closing as basically a duplicate of #415 (and I think this particular issue is sorted)
