### ISSUE TITLE
Add easter egg/celebration screen when get to the end of a volume/task queue

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#289]
Currently nothing happens when we reach the end of a project.

**Comment by mialondon** [comment]
People who finish a volume should get a lovely, motivating message congratulating them or mentioning what happens to the volume's data now. Currently it seems people are still getting an error message if the volume was finished by someone else while they were still working on it, so we might need to consider the conditions for triggering this quite widely.

**Comment by alexandermendes** [comment]
As shown in the commits linked above there is a celebration/thank you message when people complete a project! The 403 - forbidden message means that one person tried to submit an answer for the same task twice. Unfortunately in the BL we're all going through a static IP so this could also mean that two people sitting next to each other loaded a new task at the same time and the second person is denied from submitting...but that's a different issue.

**Comment by alexandermendes** [comment]
If we want to update the thank you message lets cover that here: https://github.com/LibCrowds/libcrowds/issues/555

There is also another issue open for improved error messages.

It would be helpful to lean towards creating new issues rather than reopening too many old ones, even if they are somewhat related! It makes it a bit confusing to track what was actually done and know how we can whittle down this still large list of issues!

**Comment by mialondon** [comment]
I don't think this one is solved - a thank you message isn't the same as an easter egg.

**Comment by alexandermendes** [comment]
Ok, I don't quite get what this should be then. Is it a new page that the user is redirected to? Maybe there's an example of a project that does what you're thinking of.

**Comment by alexandermendes** [comment]
I think I'll make the content of the thank you/celebration popup into yet another config option.

**Comment by alexandermendes** [comment]
Just released a component that we can use for this: 
https://github.com/alexandermendes/vue-confetti

There will be a configurable message that appears along with this falling confetti animation.

**Comment by alexandermendes** [comment]
After the update has been pushed you can see the docs for info on how to update the different types of celebration message.
