### ISSUE TITLE
Task objectives on the project cards should be more prominent

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#343]
The huge and long titles are currently too overpowering and the objectives, which are essentially the most important part, are not that visible. Either swap these round, or just play around with the design.

**Comment by mialondon** [comment]
@alexandermendes do you mean e.g.  'Transcribe Dates: Theatre Royal, Margate 1796-1797' vs 'Type in the dates on historic playbills and make them easier to find.' Perhaps the larger one could decrease a little in size and the other increase?

**Comment by alexandermendes** [comment]
Yeah exactly, or another option is just changing the titles to "Transcribe Date", "Transcribe Title" etc., Although we would end then up with multiple projects with the same main titles. This normally wouldn't be an issue as we should only have one of each per volume but might be problematic where listing projects from multiple volumes on the same page (e.g. the feature projects page).

**Comment by alexandermendes** [comment]
An example, I think this might be a good solution, maybe then also listing the category in small type on the card (e.g. Margate 1796-1797)

![screenshot](https://user-images.githubusercontent.com/5636273/30982420-40efbdaa-a47f-11e7-97a5-
44ef4bfea3c4.png)

**Comment by alexandermendes** [comment]
@LibCrowds/playbills So, we're going for something like the above right? But also including the category name below the new titles, styled differently (smaller text in italics, or whatever).

**Comment by mialondon** [comment]
@alexandermendes could we quickly mock it up in the inspector to reality check it?

**Comment by alexandermendes** [comment]
So I guess something like this:

![screenshot](https://user-images.githubusercontent.com/5636273/31173090-1655d8d0-a8fe-11e7-947b-8d368cc06d00.png)

**Comment by alexandermendes** [comment]
Should do the job of making the objective of each project clear...probably not something worth spending a huge amount of time on

**Comment by mialondon** [comment]
@alexandermendes looks good! 

If we're tailoring the card interface, can x tasks read x playbills, and 'join x volunteers'?

**Comment by alexandermendes** [comment]
So we can have a go, although this would require a more significan't redesign - obviously the extra words don't fit onto the cards as they are...

We might also want to think about the other places that "task(s)" appears throughout the site. If we change it to playbills only on the cards are we later going to say we also want to change it on page X and Y? At the moment it's easy - the terminology for category, project, task and task run can be changed via the microsite settings (see below) but this will change all instances of those words...

https://github.com/LibCrowds/libcrowds-frontend-settings/blob/a267905bf70a15fcba258a9bda69d340f916ad95/playbills/config.js#L48-L54

Eventually I want this all configurable via the admin interface and we should probably discuss going for that after various other features are in place - then it can be up to the "owners" of each project to edit as they like.

**Comment by alexandermendes** [comment]
P.S. I missed that you did consider that and shortened it to "Join X volunteers" - so that part should be fine!

**Comment by alexandermendes** [comment]
Also, I agree that playbills looks nicer on the cards. Just want to make sure we know what we're changing, before I put another config variable in place.

Of course, I'm changing this for the card conversion and all other future projects, not just the playbills microsite, so everything has to be done via configuration files.

A separate config for just the cards is definitely possible

**Comment by mialondon** [comment]
@alexandermendes considering the importance of the cards in 'marketing' the projects, I think it's worth it!

**Comment by alexandermendes** [comment]
Ok cool, so we'll go for some way of modifying just the card stats text.

**Comment by alexandermendes** [comment]
Moving this to the next version as it sounds like we now need a more configurable design. Not a huge task but I don't want to hold up today's release.

**Comment by alexandermendes** [comment]
This will be part of expanding the config options for projects, so won't make it today, moving to the next release (again)!

**Comment by mialondon** [comment]
We probably need a proper planning session for config options, it's all grown rather organically.

**Comment by alexandermendes** [comment]
Sure, although that's not to say that it's all been haphazard, many hours of thought have obviously gone into each feature! Let's chat sometime about what you, Christian or anyone else actually want to be able to modify via the interface, then we can build a way of doing that. Rather than focusing on what the particular input fields are and how every option actually works (which will of course be documented).

**Comment by alexandermendes** [comment]
I think we can close this now. The cards are pretty much sorted with extra attention drawn to each task type via the configurable tags. We can't make every detail configurable as it will never get used after the initial setup anyway.
