### ISSUE TITLE
Update share button and use it to better guide people into the forum

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#344]
We probably want to avoid messages that are too invasive (e.g. saying "do you want to discuss this playbill" after every submission) but something along those lines...perhaps just a similar message after every 10 tasks. 

Could this also be linked to the "like" button? So if they click like then ask if they also want to discuss it.

**Comment by mialondon** [comment]
Hmm, that might be weird. I think a 'discuss this on the forum' button is more obvious, but we'll still need to explain how to copy the exact URL for an item. Or if the 'share' function behaved more like UV, there'd be space for brief explanatory text. (I'm assuming that prep-populating forum posts with the link isn't possible.)

**Comment by alexandermendes** [comment]
Yep, so another option would be to put a "Discuss this playbill" button above the current note button - although, we now seem to be getting back to our long standing discussion about what the purpose is of each of those functions!

**Comment by alexandermendes** [comment]
So, I like the idea of a "Discuss this playbill" button and having the note button be more along the lines of "Noticed and issue? Add a note".

**Comment by mialondon** [comment]
On the 'share' button, a bit to copy the link and a link to the 'spotted something interesting' thread.

**Comment by alexandermendes** [comment]
So I think the current decision here is to start by building this into the Share button popup? So that will include an option to copy just the link, or copy the link and go to the forum.

**Comment by mialondon** [comment]
Yep!

**Comment by alexandermendes** [comment]
Ok great.

(Note to self - also close #365 when this is done)

**Comment by alexandermendes** [comment]
@mialondon So I've started adding this as a modal the shows when the share URL is clicked (we already had the code and it's the same behaviour for other buttons on the toolbar). Before I go any further could you check out the demo page?

Note that it's only there in "select mode" (for the demo).

https://libcrowds.github.io/libcrowds-viewer/

**Comment by alexandermendes** [comment]
There would then be a space at the top where a config variable can be used to fill in whatever text we like, as with the help modal.

**Comment by alexandermendes** [comment]
@mialondon Ah, so we just need the text for this - as we're regenerating tasks anyway. Again, this can be created on a task-by-task basis, so we could potentially have different text for genre/title/person etc, but we probably don't need to go that far.

**Comment by alexandermendes** [comment]
Can just go in here for the time being https://github.com/LibCrowds/project-playbills/blob/master/config/share/all_tasks.md

We can look at generating separate files for each task type later

**Comment by alexandermendes** [comment]
The text gets updated when new tasks are generated but the functionality is there.
