### ISSUE TITLE
Make better use of the intro text on the contribution page

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#352]

**Comment by mialondon** [comment]
@alexandermendes a simple solution for documenting which text is updated where could be to annotate screenshots with the underlying location of different bits of text

**Comment by alexandermendes** [comment]
I wonder if this is something for our wiki. 

Basically, configuration options for the site as a whole are here: https://libcrowds.gitbooks.io/vue-pybossa-frontend/content/configuration.html (I think the one we're talking about there is the About page text, I guess we should also add one for the 'Contribute' page text).

Configuration options for projects are here: https://github.com/LibCrowds/project-playbills

**Comment by mialondon** [comment]
The README.md is out of date, btw!

**Comment by alexandermendes** [comment]
Ok, which one? The docs generally do need a bit of work but they are getting there (slowly)!

**Comment by mialondon** [comment]
https://github.com/LibCrowds/project-playbills/tree/master/config - references tutorials rather than help folder.

**Comment by alexandermendes** [comment]
Ok thanks, updated. I might look at a different solution for editing help files if they're going to be changing a lot, but this works for now (even if it isn't a nice as a web interface)!

**Comment by alexandermendes** [comment]
I wonder if we actually need to bother with any text at the top of the 'Browse Projects' page. Once people have navigated here and are presented with a list of projects and big green contribute buttons it should be pretty obvious what they need to do. If we look at some other projects, they just assume that people know how to deal with a list of projects:

https://transcription.si.edu/browse?filter=all
https://www.zooniverse.org/projects
http://menus.nypl.org/menus
http://ensemble.nypl.org/programs

Just a thought, but I am starting to think that more text everywhere isn't always the answer! In fact, it starts to get in the way at some point - short internet attention spans and all that. Might be nicer to just have a cleaner browse/sort interface - maybe changing the title to 'Browse Projects' is the only description we need...

**Comment by mialondon** [comment]
Decision to make the text editable

**Comment by mialondon** [comment]
@alexandermendes I can set aside some time to write text for this on Thursday - if there's nowhere to add it directly by then I can email it to you

**Comment by alexandermendes** [comment]
Cool, thanks. I'll have a look at this one now.

**Comment by alexandermendes** [comment]
So you can just add it here for now:

https://github.com/LibCrowds/libcrowds-frontend-settings/blob/master/playbills/contribute.md

Like with the about page, it will update each time the site is rebuilt (which happens when new branches are merged in). Eventually it would be nice to have it be editable via the interface but I don't think it's a priority right now when this does the job!
