### ISSUE TITLE
Convert-a-card: fields from Worldcat not displaying correctly in search results 

### ISSUE THREAD

**Issue by ndalyrose** [LibCrowds/libcrowds#370]
Example attached. I wonder if it has to do with punctuation? Not sure.   
![libcrowdserror](https://user-images.githubusercontent.com/5773948/31176634-71826900-a90b-11e7-8518-19081f22258b.png)

**Comment by alexandermendes** [comment]
Thanks!

It could be a strange text processing thing, or probably just me picking the wrong MARC fields for titles (using 245a/b/c at the moment). I'll check it out.

https://github.com/LibCrowds/vue-pybossa-frontend/blob/56a05ed4d253f418df2ddbc9948dd882061b5a55/src/components/presenters/Z3950.vue#L435-L460

**Comment by alexandermendes** [comment]
Give it 10 mins or so and you should see the fix on the dev site!

**Comment by alexandermendes** [comment]
Fixed on the dev site - new version being pushed to the live site today
