### ISSUE TITLE
Convert-a-card: Allow download of card images

### ISSUE THREAD

**Issue by ndalyrose** [LibCrowds/libcrowds#371]
Can we add the option that allows download of all the card images back in please? Or include a pointer to where they're available for that on data.bl.uk. https://data.bl.uk/aas_cardcatalogues/

**Comment by alexandermendes** [comment]
Yep! So this will be part of the functionality of the new "Browse Results/Analysis" section (https://github.com/LibCrowds/vue-pybossa-frontend/issues/277). I've got this in the queue to (optimmistically) deal with before the next release on Monday.

**Comment by alexandermendes** [comment]
Oh but in terms of just adding links and so on, you can always update the about page text - here:

https://github.com/LibCrowds/libcrowds-frontend-settings/tree/master/convertacard/about

The intro section appears at the top and the rest below.

Eventually we'll have this editable via the interface but we're not there yet.

**Comment by alexandermendes** [comment]
The content for each microsite is now configurable via the admin interface, so you can update the Convert-a-Card pages however you like. Still some docs to write up but if you remind me I can show you this week!
