### ISSUE TITLE
Same playbill keeps re-appearing

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#378]
As reported on https://community.libcrowds.com/d/13-same-playbill-keeps-re-appearing

**Comment by alexandermendes** [comment]
Yeah, this is definitely a high priority fix...I'll looks at this today, comething seems to have gone wrong with the task generation.

But, we can use this opportunity to update our help/guidance text. I might have to close the projects, download the data, fix the task generation and regenerate, then load the contributions back in. Luckily we haven't had too many yet.

**Comment by mialondon** [comment]
@alexandermendes is there any text that needs a final review/tweak before it's copied over?

**Comment by alexandermendes** [comment]
We'll we have something there now for all of the help files, so unless there's anything you want to change I think it should all be ok.

**Comment by mialondon** [comment]
Let's see what our generous usability tester makes of the changes and review if necessary!

**Comment by alexandermendes** [comment]
Yep ok, although that means we have to regenerate the tasks multiple times! I wonder if we might need another answer here, but again, wasn't expecting the text would need to be changed so frequently

**Comment by mialondon** [comment]
It should settle down once we've got the basic tasks set up. 

If the dev site was able to pull in the latest text easily, it'd make iterating and testing easier. Something to think about?

**Comment by alexandermendes** [comment]
So the dev site is using the same database as the live site.

This is the thing about tasks being generated and stored in the database. There's no easy way to then go in and update every task after generation. It's possible to write scripts to do this, of course, but it wouldn't be a small change!

**Comment by mialondon** [comment]
Indeed! It does limit the usefulness of the dev site to an extent, because you can't just try something out and see how it goes, but rather need to plan to be sure that you'll be happy with the text later.

**Comment by alexandermendes** [comment]
Well we can easily set up another backend, but again it's more work/time/money, if we feel it's worth it we always have that option

**Comment by mialondon** [comment]
There's more information on the original bug report at https://community.libcrowds.com/d/13-same-playbill-keeps-re-appearing/2

**Comment by alexandermendes** [comment]
Oh thanks, I'll drop in and reply there.

I think it's related to this issue (pagination broken when retrieving tasks via the API):

https://github.com/Scifabric/pybossa/issues/1667

**Comment by mialondon** [comment]
Thanks!

(I missed the replies at the time, the icon stayed white rather than going black)

**Comment by alexandermendes** [comment]
Closing, see above
