### ISSUE TITLE
Make help/tutorial text editable via the admin interface

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#388]
This issue of being able to edit task guidance/help etc. after tasks are generated is coming up a lot. I propose building in a way to edit certain task info keys via the project admin interface.

**Comment by mialondon** [comment]
Sounds sensible, thanks! Do you have an estimate for the time that might be required?

**Comment by alexandermendes** [comment]
A little tricky as it's a somewhat new problem but we should be able to sort something out on the frontend in a few hours. Depends how pretty etc. we need it to be! However, it will also rely on https://github.com/Scifabric/pybossa/issues/1697#issuecomment-334704004 being fixed.

I think this should probably be one for next week.

**Comment by mialondon** [comment]
Yep, sounds good to me.

**Comment by alexandermendes** [comment]
We'll also want to build in the rules for when to show the confirm dialogue. For example, where tag = title, mode = select and nAnnotations < 2 we show the confirm dialogue, but this will obviously be different for every type of task.

**Comment by alexandermendes** [comment]
There are a couple of options built in now and more will follow. Making every bit of text for every task editable seems like overkill and would get a bit tricky, we have a lot of config options coming in now that no one is actually going to end up using. At some point we'll have to say you generate a task with options x and y and once you publish it that's it. Even if say the objective text for all tasks was editable now, who is going to go back and change them for all tasks in all projects? Not me!

We'll make the main help/tutorial text editable for all projects. If it actually becomes a used feature (which I suspect not) we can reconsider widening it.

**Comment by alexandermendes** [comment]
Help text will now be configurable at the project level. In reality we probably don't want to go in and change this all the time as it has to be done per project (they're all different) but the option is there if there are any urgent updates.

We're also going to have a templating option for generating new projects, similar to our current JSON/Python scripts setup but built into the interface. The help content for all future projects will be configured there.

**Comment by alexandermendes** [comment]
Oh and note button text and submit button text is also configurable at a collection level. Probably more to follow but we also don't want to overwhelm people with options!

**Comment by mialondon** [comment]
Can you include the docs link?

**Comment by alexandermendes** [comment]
docs.libcrowds.com

Still a work in progress of course but it's getting better. I suspect the next thought will be that there is too much there for people to understand, but most of those settings will remain hidden from 99% of people. Project generation will happen from a set of templates, designed by administrators. That should be there this week.

**Comment by alexandermendes** [comment]
For the help text bit specifically https://docs.libcrowds.com/project_settings/help/
