### ISSUE TITLE
Update zenodo badge to always show the latest DOI

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#392]
Currently it's showing a specific DOI (for v1.0.0-alpha.2)

**Comment by alexandermendes** [comment]
Hmm, actually the link is correct, not sure why the badge isn't updating in the README

**Comment by alexandermendes** [comment]
Closing as the markdown is correct, not sure why the image isn't updating but not something I can fix. Maybe it's cached by GitHub somewhere...

**Comment by Juanlu001** [comment]
I'm having the same problem: the Markdown is correct, but the image does not update on GitHub rendered Readme...

**Comment by alexandermendes** [comment]
This one is now showing as the 2nd latest release, which is strange, but nothing we can do about it I suppose!
