### ISSUE TITLE
Check if we can enable the creator of a forum post to be displayed

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#396]

**Comment by mialondon** [comment]
It looks like the creator's avatar is displayed, but not their name. Ideally we'd want both name and avatar for the original poster and most recent poster.

**Comment by alexandermendes** [comment]
Yep I noticed that the avatar is indeed there. It looks like we don't have an easy way to add the name but let's leave this open until we investigate fully. It could be a case of writing a custom extension so I'm not sure if that would be worth it. Here's a list of some extensions currently available:

https://github.com/moutonnoireu/flarumextlist/wiki/Extension-List

**Comment by alexandermendes** [comment]
So I don't think we want to get into writing custom PHP extensions just for this...(?)

**Comment by mialondon** [comment]
Nope - let's just encourage more people to post!
