### ISSUE TITLE
Add a link back to the main site on the forum site?

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#400]
If someone first lands on a forum discussion, it might take them a while to find a link to a task page, as most links would be to UV pages.

**Comment by alexandermendes** [comment]
Added links back to each microsite in the forum header. Might have to revisit when more microsites are created but it is a way back to the main sites for now.

**Comment by mialondon** [comment]
I just noticed this - thank you! It came up again on Thursday, so it's very timely.
