### ISSUE TITLE
Add newsletter archive / sign-up link to site footer

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#404]
It's really hard to find unless you know there's a contact section on 'about us' for individual sites.

**Comment by alexandermendes** [comment]
Good idea, I think I had it on the list ages ago but never got around to it. We can actually have it as a text box to fill in your email and hit subscribe, rather than a link to the external mailchimp form. People are asked if they want to subscribe when they first sign up for an account, so the API integration stuff is already there in some form.

**Comment by alexandermendes** [comment]
So we can join it with this one, when we get to it https://github.com/LibCrowds/libcrowds/issues/217

**Comment by mialondon** [comment]
If a text box would fit neatly into the footer that'd be great!

**Comment by mialondon** [comment]
(There's always a chance that people will use it as a search box, but putting it the footer probably minimises the chances of that happening)

**Comment by alexandermendes** [comment]
Well I'd say at that point we can't help them. It would be a box saying "Subscribe to our newsletter" or something!

**Comment by alexandermendes** [comment]
Got half way through this last night but there are CORS issues trying to communicate with the Mailchimp API so actually not that straightforward. I'll pick it up again in the next release

**Comment by mialondon** [comment]
Can we just have a line and link saying 'subscribe to our newsletter' in the meantime?

**Comment by alexandermendes** [comment]
Sure, so I'll have another quick go as I've put a bunch of work into it already and I think it would be much cleaner to have a "Subscribe to our Newsletter" section in the footer. But if it proves too difficult we can just go with the link.

**Comment by alexandermendes** [comment]
This is done as an additional config option to add a custom footer menu, in this case being used for the above.
