### ISSUE TITLE
www.playbills.libcrowds.com should direct to playbills.libcrowds.com

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#408]
In case people automatically type it, or 'helpfully' it www to the link!

**Comment by alexandermendes** [comment]
Although actually they should both currently redirect to https://www.libcrowds.com/collection/playbills, so it's strange if you're not seeing that?

**Comment by mialondon** [comment]
The first one times out, but I've only been able to check it on hotel wifi.

**Comment by alexandermendes** [comment]
Oh, I actually misread this yesterday - www.playbills.libcrowds.com won't work, but it won't work for any other site either...

- https://www.scholar.google.co.uk/
- https://www.developers.facebook.com/
- https://www.help.github.com/
- www.explore.bl.uk

Seems overly complicated to account for every possibility, and I suppose anyone typing directly into the address bar will quickly realise they mistyped

**Comment by mialondon** [comment]
You'd be surprised! If it's possible, it'd be good to do.
