### ISSUE TITLE
Produce tweetable "on this day" content for a twitter bot etc

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#412]
Thanks to thoughts from our social media team on how to promote the platform, this is actually a pretty cool idea - an automated tweet generator that pulls in content from our transcriptions and links back to the playbills images:

> #onthisday Macbeth was performed in Sheffield with a live duck on stage http://link-to-image.com

🤔

**Comment by alexandermendes** [comment]
A really nice idea but not a priority until we have some data!

**Comment by mialondon** [comment]
I was going to play with the data in the hack and yack but couldn't find it in the completed volumes.

**Comment by alexandermendes** [comment]
Oh sorry, just saw this. The task run datasets contain all of the contribution data. The results datasets have not all been populated yet (I want to do that this week).

**Comment by alexandermendes** [comment]
Just a further note - I think this actually works better a nice example of using the API with Jupyter notebooks. Will leave this open until I write it though.

**Comment by mialondon** [comment]
There's a note for this on the 'possible features' Trello list. Is it something Beatrice could work on? I'd say it's more of a social media than a front page thing.

**Comment by alexandermendes** [comment]
Yep, hence I was closing as it's not directly to this repository - it could go in https://github.com/LibCrowds/notebooks.

Also, once we have the data and know how to use, for example, pandas to manipulate it the task itself is trivial. What we find is that we don't really have enough data yet to get something for each day of the year. The attached CSV shows all of the titles where we also have a full date. We can get more if we also use the partial dates but still, we probably need more data.

[out.zip](https://github.com/LibCrowds/libcrowds/files/2058888/out.zip)

**Comment by alexandermendes** [comment]
There is now a script in [LibCrowds/data](https://github.com/LibCrowds/data) that will produce a CSV file in the format below.

It could be updated to tweet automatically but it would be more complicated and it seems safer to keep it as a document to copy and paste from. Can be regenerated with a single copy & paste of the command to run the script to the command line.

day | month | year | tweet
-- | -- | -- | --
1 | 1 | 1827 | #Onthisday, in 1827, Black Beard Or, the Captive Princess was performed   at Miscellaneous Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=66
1 | 1 | 1827 | #Onthisday, in 1827, Irish Tutor was performed at Miscellaneous Plymouth   theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=66
1 | 1 | 1833 | #Onthisday, in 1833, Eugene Aram was performed at Miscellaneous Plymouth   theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=248
1 | 1 | 1833 | #Onthisday, in 1833, Alfred the Great was performed at Miscellaneous   Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=248
1 | 1 | 1827 | #Onthisday, in 1827, Three Wishes; Or, Harlequin's Christmas Box was   performed at Miscellaneous Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=66
1 | 1 | 1828 | #Onthisday, in 1828, Charles Ii was performed at Miscellaneous Plymouth   theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=172
1 | 1 | 1828 | #Onthisday, in 1828, Old Oak Chest was performed at Miscellaneous   Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=172
1 | 1 | 1836 | #Onthisday, in 1836, Jane Shore was performed at Miscellaneous Plymouth   theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589096.0x000002#?cv=280
1 | 1 | 1836 | #Onthisday, in 1836, Masaniello!! Or the Dumb Girl of Portici was   performed at Miscellaneous Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589096.0x000002#?cv=280
1 | 1 | 1846 | #Onthisday, in 1846, White Cat was performed at Miscellaneous Plymouth   theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589096.0x000002#?cv=11
1 | 1 | 1846 | #Onthisday, in 1846, A Grand Vocal and Instrumental Ethiopian Concert was   performed at Edinburgh theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589068.0x000002#?cv=9
2 | 1 | 1827 | #Onthisday, in 1827, Perouse: The Desolate Island was performed at   Miscellaneous Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=104
2 | 1 | 1827 | #Onthisday, in 1827, Black Beard Or, the Captive Princess was performed   at Miscellaneous Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=104
2 | 1 | 1827 | #Onthisday, in 1827, Paul Pry was performed at Miscellaneous Plymouth   theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=104
2 | 1 | 1834 | #Onthisday, in 1834, Death of Captain Cook was performed at Miscellaneous   Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=154
2 | 1 | 1834 | #Onthisday, in 1834, The Road to Ruin was performed at Miscellaneous   Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=154
2 | 1 | 1837 | #Onthisday, in 1837, No was performed at Miscellaneous Plymouth theatres   http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589096.0x000002#?cv=124
