### ISSUE TITLE
Auditing mobile issues

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#415]
Email sent to Digital Scholarship: We’ve got a quick favour to ask as we prepare to launch In the Spotlight. The playbills images don’t seem to load on some devices, but we’re not sure which ones and why. 

Please help us figure it out by loading http://playbills.libcrowds.com/ on your mobile device and tablets, and navigating to a task page (e.g. transcribe titles, genres, dates, mark titles, or https://www.libcrowds.com/collection/playbills/project/identify_titles_miscellaneous_plymouth_theatres_1796-1882_vol_1/presenter/ if you want a shortcut). Does a playbill load for you? Please email us with your device type (ideally physical model and operating system), whether the answer is yes or no.

**Comment by mialondon** [comment]
Feedback from Rob: Everything worked fine for me. Using a Lenovo P2a42 on Android 6.0.1

The task I did (transcribe titles) worked perfectly on a mobile screen...

**Comment by mialondon** [comment]
Andrew: Motorola Moto G, Android 5.1. And that sounds reasonable, it is a little trickier doing it on the small screen.

**Comment by mialondon** [comment]
Ben: I tried a few emulations on my machine here but couldn’t replicate any loss. Also tried on an actual mobile but still fine. However, two fingered panning on the image is not implemented though pinch zoom worked fine.

**Comment by alexandermendes** [comment]
Yeah I don't get why the images sometimes don't load. I think it might even be outside of our control if it's something to do with the core BL systems. But we'll try to trigger error messages when this happens and see if we can trace things back from there.

**Comment by alexandermendes** [comment]
This is the message that is sometimes shown and one to investigate further...it's certainly not unique to us

> Unable to open [object Object]: HTTP0 attempting to load TileSource

In fact, when I was at the UCL IIIF event a few days ago the guys from Digirati had trouble getting their demo worknig with BL content, something about the response not being sent correctly, I should've asked more but it was during the talk and I didn't remember to follow up

**Comment by mialondon** [comment]
Is it worth posting on https://britishlibrarydev.slack.com/messages/C6MK1J5R7 (#uviiif)

**Comment by alexandermendes** [comment]
Maybe, but I don't think we have enough info yet! All we can say that we occasionally have issues retrieving BL images via the IIIF Image API and we don't yet know why

**Comment by alexandermendes** [comment]
Ok, so I think the disappearing images are a CSS thing, we need to test more but I'll tackle some of it here https://github.com/LibCrowds/libcrowds/issues/446

**Comment by alexandermendes** [comment]
Would suggest this one moves to our Trello notes too...there isn't really any issue to solve here!

**Comment by alexandermendes** [comment]
Closing as there isn't anything left to do here!
