### ISSUE TITLE
LibCrowds Viewer downloads not working on Firefox

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#466]

**Comment by mialondon** [comment]
Seems to be working now.

**Comment by alexandermendes** [comment]
Oh yeah, thanks, I did sort it out for Firefox...it doesn't work in IE though so I'll add a new issue for that

**Comment by alexandermendes** [comment]
See https://github.com/LibCrowds/libcrowds/issues/497
