### ISSUE TITLE
Send email to crowdsourcing@ email when a comment is submitted during task

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#48]
_From @mialondon on August 1, 2017 15:13_

For now we'll have to manually check for them... 

_Copied from original issue: LibCrowds/libcrowds-viewer#137_

**Comment by alexandermendes** [comment]
This is not a small piece of work to do per contribution. What we can do is handle this via our results analysis server once all contributions for a task have been submitted. As you say, we can just check them manually via the data page for now.

**Comment by alexandermendes** [comment]
This will eventually be moved to the results server, when refactoring begins there.

**Comment by mialondon** [comment]
Can you provide a direct link for curators to check for comments?

**Comment by alexandermendes** [comment]
It's already all there in the downloadable datasets, which works for now. The idea was that they would also show up via the results analysis interface - basically what happens now for the convert-a-card projects, although ours will look a bit nicer.

**Comment by alexandermendes** [comment]
As mentioned elsewhere I really think the notes should be used to draw our attention to things we might need to know while processing the data, rather than encouraging it's use as a direct point of contact. We have a forum and other points of contact for that.

**Comment by mialondon** [comment]
I still think forums are a bit too heavyweight for simple comments. Definitely one that in-person usability testing will help answer!

**Comment by alexandermendes** [comment]
This will be done as part of the https://github.com/LibCrowds/libcrowds-analyst module

**Comment by alexandermendes** [comment]
So this is an old one now but I don't think we really want to receive emails every time someone writes "Not a title" etc. Comments will now always be available for download separately (or searchable via the API) so perhaps someone can go in once a week or whatever and scan through them.

**Comment by alexandermendes** [comment]
Won't do it yet but would vote to close this!

**Comment by mialondon** [comment]
We get emails whenever a process fails and at least the comments might be interesting! Email filters mean lots of emails won't be oppressive.

**Comment by alexandermendes** [comment]
Ok, so this will only apply to new comments as otherwise we'll be hit with thousands whenever we decide to regenerate results for a project, which happens whenever the analysis rules are updated (e.g. we decide to trim punctuation, or otherwise).

**Comment by alexandermendes** [comment]
So the easiest way to do this is to email the comment annotations as they're generated, example generated during testing below. Note that these annotations will also be updated to include some kind of link to the raw image.

---
Hello,

The following comment has just been generated:

```
{
  "@context": "http://www.w3.org/ns/anno.jsonld", 
  "body": {
    "format": "text/plain", 
    "purpose": "commenting", 
    "type": "TextualBody", 
    "value": "Not a playbill. "
  }, 
  "created": "2018-03-01T10:38:30Z", 
  "generated": "2018-03-01T10:38:30Z", 
  "generator": {
    "homepage": "http://127.0.0.1:8080", 
    "id": "https://github.com/LibCrowds/libcrowds", 
    "name": "LibCrowds", 
    "type": "Software"
  }, 
  "motivation": "commenting", 
  "target": "https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x000094", 
  "type": "Annotation"
}
```

Note that these messages can be disabled by setting EMAIL_COMMENT_ANNOTATIONS
to False in the main PYBOSSA settings file.

Thanks,
LibCrowds Team

---

**Comment by mialondon** [comment]
Hoorah, but json isn't very curator-friendly...

**Comment by alexandermendes** [comment]
Ok, this feels a bit like a supplementary function that I don't see getting much use though - what do we actually do once we receive the 500th email that month saying "Not a playbill"? Sending the actual annotation seemed like the cleanest way and I don't think the JSON should be that scary! We could append the actual comment value to the top of the email too?

Comments are also available for download in bulk via the data page. Ultimately, I think we should also display them in our browse/review interface.

**Comment by mialondon** [comment]
It's a really strong signal that we need to update the instructions, tutorial or whatever to stop people marking things that aren't playbills, or rethink what we're asking people to mark. 

Most of the 'generator' information is of limited value, but would it be possible to see who's commented? It'd give us a strong signal re engaged users and/or people we could test instructions with. Assuming they're not all me and Christian...!

**Comment by alexandermendes** [comment]
Well these are the actual Web Annotations and there are, of course, reasons why all of those keys exist. For example, the generator is added to all annotations so that any clients consuming the annotations (e.g. IIIF Viewers) have some information about where the annotations came from.

As comments are submitted from one person, we could add a `creator` key, although this will only appear for users that were signed in at the time. The annotations can be used to format the email differently.

**Comment by mialondon** [comment]
The link provided in the email doesn't currently work, and it doesn't look like it has hash parameters to open up at the annotated page/region - e.g. I want to check out the possible spelling error in this recent email:


Hello,       The following comment has just been generated:           {  "@context": "http://www.w3.org/ns/anno.jsonld",   "body": {    "format": "text/plain",     "purpose": "commenting",     "type": "TextualBody",     "value": "Spelling mistake in title?"  },   "created": "2018-03-01T16:24:59Z",   "generated": "2018-03-01T16:24:59Z",   "generator": {    "homepage": "https://www.libcrowds.com",     "id": "https://github.com/LibCrowds/libcrowds",     "name": "LibCrowds",     "type": "Software"  },   "motivation": "commenting",   "target": "https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589044.0x000230",   "type": "Annotation"}           Note that these messages can be disabled by setting EMAIL_COMMENT_ANNOTATIONS   to False in the main PYBOSSA settings file.       Thanks,    LibCrowds Team
--

**Comment by alexandermendes** [comment]
So those links are correct for what they are - the target is supposed to be the canvas, rather than a share link to the UV or anything like that. As above, we'll find a way to add a link to the raw image into the annotations.

For now, the item in question is http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589044.0x000002#?cv=254

**Comment by mialondon** [comment]
'Misantrophy'? Also on that page, it's interesting that the Taming of the Shrew is the alternate title, not the main title.

**Comment by mialondon** [comment]
How are the canvas references translated into workable links? A comment mentioned https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589154.0x0000d7 and I'd like to see which volume it is.

**Comment by alexandermendes** [comment]
It's a bit of a roundabout way for now but the target can be replaced in this API call:

https://www.libcrowds.com/api/result?info={"annotations":[{"motivation":"commenting","target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589154.0x0000d7"}]}

I can't actually see any comments for that target though, so if we take a working one as an example:

https://www.libcrowds.com/api/result?info={"annotations":[{"motivation":"commenting","target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589158.0x000094"}]}

Then from that response you find the `task_id` and feed that into this:

https://backend.libcrowds.com/api/task/67480

The response to that one contains a `shareUrl`, in this case:

http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589158.0x000002#?cv=24

**Comment by alexandermendes** [comment]
Ok, there is a comment that has been made but we haven't run results analysis for all of our projects, which is when the emails are generated, so to get comments made but not fed through into final results we can do

https://www.libcrowds.com/api/taskrun?info=[{"motivation":"commenting","target":"https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589154.0x0000d7"}]

Get the task ID and:

https://www.libcrowds.com/api/task/81660

The shareUrl is:

http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589154.0x000002#?cv=60

**Comment by alexandermendes** [comment]
I would suggest that it's worth waiting until a link to the image is put into the annotations though!

**Comment by alexandermendes** [comment]
So how about we format the emails like so:

---

The following comment has been made:

**User**: where known
**Comment**: Some comment
**Source**: link to image

---

**Comment by mialondon** [comment]
And that's a brilliant playbill - all the fonts, and it's so hard to work out what to count as a performance. There aren't immediately obvious works or song titles (unless you count music played on glasses) but lots of acrobatic and animal acts.

**Comment by mialondon** [comment]
I'm loving the comment emails, btw. It's so nice to get a sense of people's activities, even if I sometimes feel bad that they encounter the same issues several times in a row.

**Comment by alexandermendes** [comment]
Good to hear! :smile:

**Comment by alexandermendes** [comment]
@mialondon The user that made the comment has now been added to the emails, along with the actual image. Can you have a look at our inbox and see what you think?

Note that you might have to right click and "Download Image" but this is the Outlook blocking the images at the BL and not anything we can control.

**Comment by alexandermendes** [comment]
From email feedback - let's add the share URL back to the IIIF viewer (for IIIF projects) and Flickr (for Z3950 projects). Then we're probably ready to close!

**Comment by alexandermendes** [comment]
Share URL added!

**Comment by mialondon** [comment]
It's great! Seeing the emails come in is a great way to keep in touch with what people are working on, and for finding cool things on the playbills, and now it's really easy to go and share that on social media.
