### ISSUE TITLE
Can't clear filters once selected

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#481]
Go to the Sorting options box on https://www.libcrowds.com/collection/playbills/projects

Select a filter option e.g. a Location

Try to unselect the filter option e.g. Location

**Comment by alexandermendes** [comment]
I think this is an irritating quirk where you have to scroll down again do trigger the new results to load, will add this to the list

**Comment by mialondon** [comment]
As discussed, the issue is actually that it's not obvious how to clear filters once they've been added (also red/green colours won't work for colour blind people), but making it so you don't need to scroll to refresh would also be a very handy thing!

**Comment by alexandermendes** [comment]
Ok, both noted, I'll sort something out!
