### ISSUE TITLE
Images for each volume/project e.g. of theatre

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#49]
_From @mialondon on August 1, 2017 14:45_

_Copied from original issue: LibCrowds/libcrowds-viewer#135_

**Comment by alexandermendes** [comment]
This falls outside any kind of repo updates but we can leave it here as a note for now! Project thumbnails can be updated at any time via the website.

**Comment by alexandermendes** [comment]
We now have automated thumbnails for each project so probably don't need to worry about this too much :smile:. Using custom images also means a tiny bit of extra work each time, but again custom images will override the automated previews and can be uploaded via the website whenever.

**Comment by mialondon** [comment]
The thumbnails are part of the 'sales' process, so the better they reflect the material the better. Where do we add custom images?

**Comment by alexandermendes** [comment]
Will deal with this here https://github.com/LibCrowds/vue-pybossa-frontend/issues/295

**Comment by mialondon** [comment]
Portsmouth
![digital store 1763 a 5 portsmouth](https://user-images.githubusercontent.com/380763/30906207-08c89804-a36f-11e7-9247-4e3ff639ea35.jpg)

Interior, Covent Garden
![digital store 1763 a 5 interior covent garden theatre 1808](https://user-images.githubusercontent.com/380763/30906214-0f1fed74-a36f-11e7-8bb5-790e2fd954ee.jpg)

Margate
![digital store 1763 a 5 margate](https://user-images.githubusercontent.com/380763/30906219-12c8d8c8-a36f-11e7-97c3-370ac7414dd1.jpg)

Drury Lane
![digital store 1763 a 5 drury lane 3](https://user-images.githubusercontent.com/380763/30906223-18cedeac-a36f-11e7-844e-63d16a623376.jpg)
![digital store 1763 a 5 drury lane 2](https://user-images.githubusercontent.com/380763/30906225-1a959d02-a36f-11e7-8bb0-28dcfb19e8b6.jpg)
![digital store 1763 a 5 drury lane](https://user-images.githubusercontent.com/380763/30906233-1d8977cc-a36f-11e7-8304-342f2c94366e.jpg)

**Comment by mialondon** [comment]
Exterior views of the New Theatre Royal, Covent Garden
![digital store 1763 a 5 exterior new theatre royal covent garden 2](https://user-images.githubusercontent.com/380763/30906260-3f027f48-a36f-11e7-8435-58ade04fe772.jpg)

![digital store 1763 a 5 exterior theatre royal covent garden](https://user-images.githubusercontent.com/380763/30906294-5c4f7e02-a36f-11e7-98cd-58b5547b48e6.jpg)

Another interior, Covent Garden
![digital store 1763 a 5 interior theatre royal covent garden](https://user-images.githubusercontent.com/380763/30906324-6b3f76ba-a36f-11e7-8692-efcbfa30616d.jpg)

'View', Covent Garden
![digital store 1763 a 5 view covent garden](https://user-images.githubusercontent.com/380763/30906340-7549e8e8-a36f-11e7-9c36-c914c1919305.jpg)

**Comment by mialondon** [comment]
Bath
![digital store 1763 a 5 bath](https://user-images.githubusercontent.com/380763/30906348-7bd5ec7a-a36f-11e7-8654-79c7c55340d8.jpg)

Plymouth
![digital store 1763 a 5 plymouth](https://user-images.githubusercontent.com/380763/30906354-81d31a76-a36f-11e7-9cea-a7553d627de1.jpg)

Liverpool
![digital store 1763 a 5 liverpool](https://user-images.githubusercontent.com/380763/30906361-89ac8ce6-a36f-11e7-8281-39eec6a3818d.jpg)

Drury Lane
![digital store 1763 a 5 drury lane](https://user-images.githubusercontent.com/380763/30906368-9430ea4a-a36f-11e7-9d96-4971205e62ae.jpg)

New Theatre, Birmingham
![digital store 1763 a 5 new theatre birmingham](https://user-images.githubusercontent.com/380763/30906384-a1b07320-a36f-11e7-9ee0-305b23a57b54.jpg)

**Comment by mialondon** [comment]
Unnamed interiors
![digital store 1763 a 5 unnamed interior](https://user-images.githubusercontent.com/380763/30906415-b62abb9e-a36f-11e7-870d-4ad12a51b632.jpg)
![digital store 1763 a 5 unnamed interior 2](https://user-images.githubusercontent.com/380763/30906414-b62692bc-a36f-11e7-9465-d14f2558dc4a.jpg)

All images posted here from Digital Store 1763.a.5 http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589190.0x000002

**Comment by mialondon** [comment]
Temporary images for Edinburgh, Bristol and Hull... All images posted here from Digital Store 1763.a.5 http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589190.0x000002

![digital store 1763 a 5 miss m tree](https://user-images.githubusercontent.com/380763/30906863-09b1feb6-a371-11e7-93d7-cb4d7dfbd95b.jpg)
![digital store 1763 a 5 mrs kemble as julio](https://user-images.githubusercontent.com/380763/30906864-09b25a6e-a371-11e7-8747-0d04be479efe.jpg)
![digital store 1763 a 5 mr dowton as colonel oldboy](https://user-images.githubusercontent.com/380763/30906865-09b439a6-a371-11e7-9cd7-ffb290ca1a77.jpg)

**Comment by alexandermendes** [comment]
@mialondon can we close this one? They could be attached to trello cards or just stored elsewhere, not really anything to be "completed" here though!

**Comment by mialondon** [comment]
For now it's a good reminder to get those extra volumes up...

**Comment by alexandermendes** [comment]
Would suggest that this one moves to the Trello board now - not a development issue!

**Comment by alexandermendes** [comment]
I'll close this as GitHub issues aren't really a suitable place for image storage! The issue is just as easy to search for when close anyway.
