### ISSUE TITLE
Notes for FAQ/public-facing documentation

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#52]
_From @mialondon on August 1, 2017 15:22_

Privacy Badger can block images from loading - allow it to load api.bl.uk or turn it off for the site.

_Copied from original issue: LibCrowds/libcrowds-viewer#139_

**Comment by alexandermendes** [comment]
In fact, other aspects of the site won't work well with cookies blocked, such as user session management. There is a message that pops up on first visit saying that cookies are used to improve the experience etc. but we could add something to the FAQ too.

**Comment by mialondon** [comment]
Moved to trello
