### ISSUE TITLE
Problems changing/verifying email address

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#525]
'Hi: You're probably aware of this already, but it looks like the site's having trouble verifying email addresses. I get a 404 message when I click on the confirm-email-address link in an email from LibCrowds support.'

https://community.libcrowds.com/d/15-problems-changing-verifying-email-address

**Comment by alexandermendes** [comment]
Yep, see https://github.com/LibCrowds/libcrowds/issues/516 (will close this one)
