### ISSUE TITLE
Reset note text on moving to a new task

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#528]
In the libcrowds viewer tasks

**Comment by mialondon** [comment]
See also https://community.libcrowds.com/d/16-notes-not-erasing-on-new-playbills/2

**Comment by alexandermendes** [comment]
Note to self: remove this when LibCrowds Viewer is updated
https://github.com/LibCrowds/libcrowds/blob/20671fda4a30bc96a89fecdb924291e2d6adc3ee/components/presenters/LibcrowdsViewer.vue#L155-L159

**Comment by alexandermendes** [comment]
Fixed

**Comment by mialondon** [comment]
The note button text has reverted back (?) to a previous version?

**Comment by alexandermendes** [comment]
Ok that's a different issue though - note text is now configurable via the interface. I'll update it now.
