### ISSUE TITLE
Are polygons being offset / getting out of sync with pages?

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#550]
It could just be that some people are submitted outlines that are off, but I've noticed a few pages like this so it might be a point to investigate: 
![offset polygons https___www libcrowds com_collecti](https://user-images.githubusercontent.com/380763/33020224-5ae79e7c-cdf5-11e7-82d8-6fa7fc7ccce2.png)

**Comment by alexandermendes** [comment]
I hope its people putting them in the wrong place but if you spot it again could you copy the image url and I can investigate from there - haven't found an example yet myself
