### ISSUE TITLE
Add a form to propose new collection microsites/project sets

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#632]
Collection microsites can only be created and modified by administrators, as we need to maintain some control over how and when these are added.

It would be useful to add a form for proposing a new collection microsite, or set of projects. This will allow us to collect the data we need and help those proposing new sets of projects to think about the input required.

Questions to be expanded later would include things like:

- Where are the images/sound files currently stored?
- Have they been copyright-cleared?
- Should these projects be added to a current collection microsite, or should a new one be added?
- Please describe the projects that you would like to create.
- Enter a contact email address

**Comment by mialondon** [comment]
* Which named curator or reference team member will lead on public engagement
* Which BL systems will use the data generated?

**Comment by alexandermendes** [comment]
On second thoughts I would recommend a Google form for this. We're inevitably going to end up with BL-specific questions and actually nothing in this software is BL-specific.

**Comment by mialondon** [comment]
Sounds good to me! I hadn't actually expected that it'd be built into the software.

**Comment by alexandermendes** [comment]
Ok cool, an external form was my first though, then I wondered if there was a standard way of building it in, now back to realising an external form is best, so this might just be a bit of me thinking out loud!

**Comment by alexandermendes** [comment]
Will say medium priority as it sounds like it would be useful to have something to send of to the sound heritage people soon

**Comment by mialondon** [comment]
Yes, along with wider documentation of the various stages and processes involved...

**Comment by alexandermendes** [comment]
I'm hoping a lot of that should be guided by the feedback from this form as it's largely dependant on what the project actually is, our inputs and outputs, who will take responsibility etc. It should be a good test case anyway

**Comment by mialondon** [comment]
I've copied some headings I started into https://docs.google.com/document/d/17mKNYD0vZdWdvZjC6uPZlyPpjDY3ZKKkrs1dE3_Zclw/edit?usp=sharing

**Comment by alexandermendes** [comment]
I guess we can close this or move to Trello as it's not going to be anything to do with the code in this repo
