### ISSUE TITLE
Has the 'discuss on the forum' link disappeared from the Share button?

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#634]

**Comment by alexandermendes** [comment]
Good catch, possibly happened when making it configurable at the collection-level. I can't remember what the text said exactly but if you go to **Collection Admin > Task Presenter** you can edit it as Markdown in the **Share Text** field.

**Comment by mialondon** [comment]
Thanks! I changed the link to https://community.libcrowds.com/d/11-spotted-on-in-the-spotlight
