### ISSUE TITLE
Add forum activity summary section to microsite homepages

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#679]
We can get the number of topics for each forum category via the API:

https://community.libcrowds.com/api/tags

We could use this to build a simple Discuss section on the homepage, something like:

## Discuss

25 topics are being discussed on the In the Spotlight forum, come and join in!

**Comment by alexandermendes** [comment]
Finish this off following https://github.com/Scifabric/pybossa/pull/1848

**Comment by mialondon** [comment]
Looks good! 

Is the API responsible for the ungrammatical '1 participants'?

**Comment by alexandermendes** [comment]
Ok, well spotted! Fix incoming
