### ISSUE TITLE
Remove hard limit of 100 collections

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#740]
To allow them all to be retrieved in one query, we currently have a hard limit of 100 collections before things will start to go wrong. While it's unlikely that this limit will ever be reached it's not impossible and this limit should be removed, check any calls to `/api/category`.

**Comment by alexandermendes** [comment]
Probably use a fetch mixin.

**Comment by alexandermendes** [comment]
We may hit issues with the above solution of retrieving over 30,000 objects (due to rate limiting of the API) but that is so unlikely that we probably don't really need to consider it at this stage. If we ever hit it some kind of auto-throttling can be implemented.

**Comment by Addaci** [comment]
If LibCrowds were used by the @signsofliteracy community, with the permission of the British Library, as a crowdsourcing platform,  we could easily wish to retrieve over 30,000 objects. I am assumibg that an object is an individual image and related tags or semantic annotations? We intend to build a collection of at least 50,000 images, for area markup and tagging by crowd.

**Comment by alexandermendes** [comment]
In this case I'm referring to the various domain objects retrieved via the PYBOSSA API - like category, project and task. Also, I'm referring to the all being retrieved in one go, which is really very rarely needed.
