### ISSUE TITLE
Hide projects from Take Part page if a user can no longer contribute

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#749]

**Comment by mialondon** [comment]
@alexandermendes possibly related - should completed projects show up under Featured Projects?

**Comment by alexandermendes** [comment]
So it depends how they're set. If set manually via the admin pages then we show whatever has been selected. If nothing is set then we use by default the three most recently created projects, which has the advantage of not constantly having to update the featured projects. I recently updated the API to allow us to also filter things like that by progress, so yes we should show by default the 3 most recent incomplete projects.

See https://github.com/LibCrowds/libcrowds/issues/813

**Comment by mialondon** [comment]
I'm still seeing projects I've 'completed' in the list on https://www.libcrowds.com/collection/playbills/projects

**Comment by geoffroy-noel-ddh** [comment]
Hi Mia, I don't think this bug is currently visible on the site. Shall we wait until you have managed to correct the empty projects (i.e. those with no tasks)? See #843

**Comment by mialondon** [comment]
@geoffroy-noel-ddh that sounds sensible to me!

**Comment by mialondon** [comment]
Looks like it's working.
