### ISSUE TITLE
Multiple emails per comment submitted

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#784]
It's not a biggie, but it makes it hard to find new comments among the repeats.

**Comment by alexandermendes** [comment]
Oh right, these might all be old ones from me migrating the data over the weekend to a shiny new annotation server! It basically just recreated all the results on the new server. The emails should be switched off for these bulk updates so I'll check it out.

**Comment by alexandermendes** [comment]
Can't see any recent occurrences of this issue, can reopen if it actually appears again.
