### ISSUE TITLE
Filter button weirdness

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#786]
![20180522 take part i libcrowds www_libcrowds_com_collection_playbills_projects 037](https://user-images.githubusercontent.com/380763/40354854-cf07df96-5dac-11e8-82ba-22021bce502b.png)

**Comment by alexandermendes** [comment]
A few other bugs to tackle at the same time:

- The "completed" toggle button shows through the dropdown
- hitting delete when no text is in the dropdown will cause it to attempt to search for `null`, and crash
