### ISSUE TITLE
Make tagging option more obvious - on the RHS, you can _tag this page_

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#787]

**Comment by alexandermendes** [comment]
Can we say "Tag this item" instead? Just thinking of other projects that might end up using the same viewer, where the items aren't necessarily pages.

**Comment by mialondon** [comment]
Sure. Or could the text be configurable? The reason I'm being specific is that Beatrice thought it might refer to sections of a page (e.g. marked regions).

**Comment by alexandermendes** [comment]
Ok fair point, we can add in a config option!
