### ISSUE TITLE
Add overall progress report for categories

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#811]
It's currently difficult to track where we are with each volume and template. A progress report in the form of a table would help, something like:

|              | Mark titles | Transcribe Titles |
|--------|------------|------------------|
|  Vol 1    | 100             | 75                         |
| Vol 2    | 100              | 0                           |

This can be added to both the data page and the new project form, to help determine which project should be created next.

**Comment by mialondon** [comment]
@alexandermendes where can I find this page to review?

**Comment by alexandermendes** [comment]
It's a CSV download, visible on the data page under the reports tab and the new projects page
