### ISSUE TITLE
Metadata screen for new volumes isn't loading

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#821]
e.g. https://www.libcrowds.com/collection/playbills/projects/128/iiif-annotation

**Comment by alexandermendes** [comment]
As we've seen a few times, I would assume it's your privacy plugin blocking CORS requests...probably always good first stage to check if anything appears to be broken.

**Comment by alexandermendes** [comment]
Needs further investigation!

**Comment by alexandermendes** [comment]
CORS issues solved by proxying these requests via our the backend server. There might be some headers to be fixed on the BL servers but even if that happens we couldn't guarantee we wouldn't face the same issue when later loading data from other servers. This solution means we don't have to rely on external servers having set CORS headers correctly.
