### ISSUE TITLE
Change reject modal header

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#822]
I tried searching the documentation but couldn't find the information.

Also, as I can't see the screen yet, can we change the 'Reject' title of the modal?

**Comment by alexandermendes** [comment]
The rejection reasons are defined at the template level. As an admin user, go to Menu > Project Templates > In the Spotlight > Transcribe X > Task. The rejection reasons are on that form, remember to click *Update* to save.

The global task presenter options are defined at the Collection level. Go to Menu > Collections > In the Spotlight > Task Presenter.

**Comment by mialondon** [comment]
Can I change this header?

![20180627 mark titles_ chideock to deptford 1790-1853 vol_1 i libcrowds www_libcrowds_com_collection_playbills_projects_128_iiif-annotation 051](https://user-images.githubusercontent.com/380763/41977287-df6bbcfa-7a16-11e8-9496-421ff4c4a7d7.png)

**Comment by alexandermendes** [comment]
Not via the interface but what do you want to change it to?

**Comment by mialondon** [comment]
Report an issue
