### ISSUE TITLE
Login throws an error

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#840]
@alexandermendes just in case you're around - can you help?

**Comment by mialondon** [comment]
Just had this again, Bad Request

Request failed with status code 400

**Comment by jmiguelv** [comment]
@mialondon was the error with a local account or with a 3rd party login?

**Comment by mialondon** [comment]
@jmiguelv thanks for asking! If by 3rd party you mean social media, I assume it was local.

**Comment by mialondon** [comment]
@jmiguelv in fact, I'm getting it when trying to log in now with a login for my personal email account

**Comment by jmiguelv** [comment]
Thank you for confirming, 3rd party login seems to work without issues. We will investigate the other one.

**Comment by jmiguelv** [comment]
@mialondon I am not able to replicate the login issue. I can login both with 3rd party and with separate username/password.

Can you see any errors in the browser console? Which browser/OS are you using?

**Comment by mialondon** [comment]
Actually it's working for me now... I might ask people on twitter to try logging in and let me know if they have any issues.

**Comment by mialondon** [comment]
No-one's reported any issues but the dashboard also doesn't show any returning users.

**Comment by mialondon** [comment]
A colleague using IE has reported he got the 'Uh oh, something's broken' message.

**Comment by jmiguelv** [comment]
I see the issue with IE 11 as well, it is CORS related: ```XMLHttpRequest for https://sentry.io/api/98766/store/?sentry_version=7&sentry_client=raven-js%2F3.19.1&sentry_key=378159ba3551417f8cfaa2bd2c67c17d required Cross Origin Resource Sharing (CORS).```

**Comment by mialondon** [comment]
That'd probably explain Firefox too, as it seems very CORS sensitive. Is there an easy fix?

**Comment by mialondon** [comment]
But that doesn't explain why it didn't work on one Firefox instance (my main desktop) but it did on my laptop, unless it was a cookies or plugin issue.

**Comment by jmiguelv** [comment]
The IE issue might be related to this https://docs.sentry.io/platforms/javascript/#browser-table. What versions of Firefox did you try with?

**Comment by mialondon** [comment]
On my laptop it's 68.0.1, I assume it's roughly the same on my desktop.

**Comment by adikeinan** [comment]
I get the 'Uh Oh' error message on  IE 11, when clicking on 'Sign In'. I manage to login on Chrome and Firefox (68.0.1).
