### ISSUE TITLE
Unable to open [object Object]: HTTP 0 attempting to load TileSource

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#856]
This message has started to appear on all the Playbills tasks, even ones that were previously fine. I was using the site yesterday after Christian loaded new playbills and didn't spot the issue then.

Some examples: 

https://www.libcrowds.com/collection/playbills/projects/167/iiif-annotation

https://www.libcrowds.com/collection/playbills/projects/171/iiif-annotation

I've checked and the IIIF service seems to be fine.

@harryjmoss could you take a quick look and see if there's anything obvious?

**Comment by harryjmoss** [comment]
I can't get the message to appear in chrome for Windows 7, are you still seeing the error?

**Comment by mialondon** [comment]
@harryjmoss I still see it on Firefox (Mac) but not on Safari. Possibly a CORS issue?

**Comment by mialondon** [comment]
I'm still seeing it at home but not my work Mac.

**Comment by mialondon** [comment]
I've asked on twitter to see if anyone else has the issue: https://twitter.com/LibCrowds/status/1215636762044915712

**Comment by mialondon** [comment]
I haven't been able to reproduce this at the moment.

**Comment by mialondon** [comment]
It's probably a privacy plugin issue - as long as it's not a CORS issue it's fine.

**Comment by mialondon** [comment]
Seems to be a Privacy Badger issue.
