### ISSUE TITLE
Sentry.io "IOError" notifications

### ISSUE THREAD

**Issue by harryjmoss** [LibCrowds/libcrowds#857]
Errors such as [this](https://sentry.io/organizations/libcrowds/issues/1231149721/events/95036b3921024b56a38647134ed2792b/) appearing on sentry - `IOError - write error`. Looks to be related to [this issue](https://github.com/getsentry/raven-python/issues/732) with the uWSGI config. I'll implement the fixes suggested in that issue and see if things settle down.

**Comment by mialondon** [comment]
@harryjmoss on the off-chance, is there any news?

**Comment by harryjmoss** [comment]
The fix seems to have worked, haven't seen this error popping up since November - closing this
