### ISSUE TITLE
Errors related to Image Alt Tags on welcome screen

### ISSUE THREAD

**Issue by amrinderjassal** [LibCrowds/libcrowds#874]
Please find the defects details

- 5 X Missing alternative text
-3 X Empty link

So total 8 error on welcome screen

**Comment by amrinderjassal** [comment]
Accessibility issues are resolved now on all pages.

Please find the Lighthouse reports score:-
Home page- 100/100
Playbills – 97/100
About- 100/100
Projects – 100/100
Data – 94/ 100
Browse – 94/100
Privacy – 100/100

Testing has been done with Wave evaluation tool also. No accessibility error found with it now.

**Comment by hirendrasd** [comment]
@mialondon Please check above comments and we have sent an email with details.
