### ISSUE TITLE
Zip and download KDL_Information folder from the Digital Ocean server and send to Mia

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#878]
As discussed on the call today, we'd like a copy of the files in the directory KDL_information for our files so that future developers will have an easier time with our documentation.

**Comment by ashishsinghcoforgetch** [comment]
Please find the attachment for the KDL information folder downloaded from pybossa-backend server (178.62.102.21) mailed to mia

**Comment by mialondon** [comment]
I've got the files via email so closing now.
