### ISSUE TITLE
UAT results / issues to fix now

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds#884]
Testing these core pages with Lighthouse as per the [LibCrowds accessibility fixes](https://docs.google.com/document/d/1NzZfeof4dl0PhqksHYxougZ4OCGu-vwwJUJWwqiRpIs/edit) included in the Statement of Work under the 'Scope & UAT checklist for accessibility fixes' heading:

https://www.libcrowds.com/
https://www.libcrowds.com/collection/playbills
https://www.libcrowds.com/collection/playbills/about
https://www.libcrowds.com/collection/playbills/data
https://www.libcrowds.com/help/privacy

- [ ] On https://www.libcrowds.com/help/privacy and https://www.libcrowds.com/collection/playbills/about  the `[role]` values are not valid e.g. Report https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.libcrowds.com%2Fhelp%2Fprivacy

On https://www.libcrowds.com/collection/playbills/data Report https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.libcrowds.com%2Fcollection%2Fplaybills%2Fdata 3 high errors:

- [ ] `[role]` values are not valid
- [ ] `[aria-*]` attributes are not valid or misspelled 
- [ ] Form elements do not have associated labels

On https://www.libcrowds.com/collection/playbills Report https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.libcrowds.com%2Fcollection%2Fplaybills 3 high errors:
- [ ] `[role]` values are not valid
- [ ] Buttons do not have an accessible name
- [ ] Image elements do not have `[alt]` attributes - for images in the code (as opposed to the markdown), please add empty alt tags

**Comment by amrinderjassal** [comment]
Hello Mia,

As we observed that above testing is done on prod URLS. Please try it with below dev URLS.

1.	https://dev.libcrowds.com/
2.	https://dev.libcrowds.com/collection/playbills
3.	https://dev.libcrowds.com/collection/playbills/about
4.	https://dev.libcrowds.com/collection/playbills/projects
5.	https://dev.libcrowds.com/collection/playbills/data
6.	https://dev.libcrowds.com/collection/playbills/browse
7.	https://community.libcrowds.com/t/in-the-spotlight
 
Please let us know if you face any other issue. 

Regards
Amrinder

**Comment by mialondon** [comment]
My mistake, apologies! I was trying to do the UAT while in a meeting to fit it in.

I'm still getting aria and 'tables and lists' errors on https://dev.libcrowds.com/collection/playbills/data https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fdev.libcrowds.com%2Fcollection%2Fplaybills%2Fdata

**Comment by ashishsinghcoforgetch** [comment]
Hi Mia,

I understand that you facing issue with aria and 'tables and lists' but it's related to vue - bootstrap. So when you changes this, it will automatic fixed.

Thanks

Ashish Kumar Singh
Senior Software Engineer

[cid:image001.png@01D6D7A8.8C0D7CA0]
Mobile: +91 - 7982169443
Email: ashish.4.singh@coforgetech.com<mailto:ashish.4.singh@coforgetech.com>
Coforge Limited
(Erstwhile NIIT Technologies Limited)
www.coforgetech.com<https://ind01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.coforgetech.com%2F&data=04%7C01%7CAshish.4.Singh%40coforgetech.com%7Cce59842181a541ec693508d87bd2ffed%7Cb727a530a0d54fb8bd40d8f9763e97db%7C0%7C0%7C637395493449334121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DOWz8%2FZ07KT2heGawPgvGZsQ487ZDkZHbIaFYeq7SoM%3D&reserved=0>
[cid:image002.png@01D6D7A8.8C0D7CA0]<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FCoforge_Tech&data=04%7C01%7CAshish.4.Singh%40coforgetech.com%7Cce59842181a541ec693508d87bd2ffed%7Cb727a530a0d54fb8bd40d8f9763e97db%7C0%7C0%7C637395493449354109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7tyrWnSc%2FEzIUOVDR9YDNtZX1qMEUvIWi41m0aMkSNI%3D&reserved=0>
[cid:image003.png@01D6D7A8.8C0D7CA0]<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fcoforge-tech%2F&data=04%7C01%7CAshish.4.Singh%40coforgetech.com%7Cce59842181a541ec693508d87bd2ffed%7Cb727a530a0d54fb8bd40d8f9763e97db%7C0%7C0%7C637395493449364110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SLkUXxDbl1JqN%2BUCbVIUE0442Yf5RJ9AanOfnt8cPO8%3D&reserved=0>
[cid:image004.png@01D6D7A8.8C0D7CA0]<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Fcoforge.company&data=04%7C01%7CAshish.4.Singh%40coforgetech.com%7Cce59842181a541ec693508d87bd2ffed%7Cb727a530a0d54fb8bd40d8f9763e97db%7C0%7C0%7C637395493449374104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yYJ8ltIO4568sZFIzVYOerQgeASw46NMzyuzpghzXAU%3D&reserved=0>
[cid:image005.png@01D6D7A8.8C0D7CA0]<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUC-9Vk052THg8iIOJQQNUkqQ%2F&data=04%7C01%7CAshish.4.Singh%40coforgetech.com%7Cce59842181a541ec693508d87bd2ffed%7Cb727a530a0d54fb8bd40d8f9763e97db%7C0%7C0%7C637395493449384099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5hC6P%2F2UEfnYPCk8HRAn%2BsdLwEb3eQg5Knd2vzyX7DA%3D&reserved=0>

Out of Office : None

**Comment by mialondon** [comment]
@ashishsinghcoforgetch can you outline the steps needed to resolve the vue-bootstrap issue?

**Comment by hirendrasd** [comment]
@mialondon I think there is only one issue is pending related vue-bootstrap and there is an old version of vue-bootstrap so can't update it because it may impact other areas of the portal.

**Comment by mialondon** [comment]
@hirendrasd is it currently blocking deployment?

Looking for instances of the library being imported, it mostly seems to be on information pages, so updating it might have minimal impact. However, it's the not knowing that makes it hard. Is it possible to test on a separate branch?

According to https://github.com/LibCrowds/libcrowds/blob/master/package.json the version used is "bootstrap-vue": "^2.0.0-rc.6", and the most current version on https://bootstrap-vue.org/docs/reference/changelog is v2.21.2 so there could be quite a few changes from the rc version.

**Comment by hirendrasd** [comment]
@mialondon It's not blocking the deployment. We have already deployed the changes on dev server from master branch. All looking good. Let me plan for production deployment. We can discuss on bootstrap-vue later.
